import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, Sparkles, Target, TrendingUp } from "lucide-react";
import { useInterview } from "@/contexts/InterviewContext";

const Index = () => {
  const [roleInput, setRoleInput] = useState("");
  const navigate = useNavigate();
  const { generateQuestions } = useInterview();

  const handleStartInterview = async () => {
    if (roleInput.trim()) {
      await generateQuestions(roleInput);
      navigate("/interview");
    }
  };

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Questions",
      description: "Get role-specific technical questions generated by advanced LLMs",
    },
    {
      icon: Target,
      title: "Real Interview Practice",
      description: "Practice with questions similar to FAANG interviews",
    },
    {
      icon: TrendingUp,
      title: "Detailed Feedback",
      description: "Receive comprehensive evaluation with strengths and improvement areas",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-subtle">
      <div className="container mx-auto px-4 py-16">
        <div className="mx-auto max-w-4xl">
          {/* Hero Section */}
          <div className="mb-12 text-center animate-in fade-in-50 duration-700">
            <div className="mb-6 flex justify-center">
              <div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-primary shadow-glow">
                <Brain className="h-10 w-10 text-primary-foreground" />
              </div>
            </div>
            <h1 className="mb-4 text-5xl font-bold tracking-tight text-foreground">
              AI Interview Preparation Platform
            </h1>
            <p className="mx-auto max-w-2xl text-xl text-muted-foreground">
              Generate role-specific technical interview questions powered by LLMs.
              Practice, improve, and ace your next FAANG interview.
            </p>
          </div>

          {/* Role Input Card */}
          <Card className="mb-12 border-2 shadow-lg animate-in fade-in-50 duration-700 delay-100">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-2xl">
                <Sparkles className="h-6 w-6 text-primary" />
                Get Started
              </CardTitle>
              <CardDescription className="text-base">
                Enter your target role to begin your AI-powered interview preparation
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <Input
                  type="text"
                  placeholder="e.g., Amazon SDE2, Google SWE, Meta Senior Engineer"
                  value={roleInput}
                  onChange={(e) => setRoleInput(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && handleStartInterview()}
                  className="h-14 text-lg"
                />
              </div>
              <Button
                onClick={handleStartInterview}
                disabled={!roleInput.trim()}
                className="h-14 w-full text-lg font-semibold shadow-md hover:shadow-lg transition-all"
                size="lg"
              >
                Start Interview
              </Button>
            </CardContent>
          </Card>

          {/* Features Grid */}
          <div className="grid gap-6 md:grid-cols-3 animate-in fade-in-50 duration-700 delay-200">
            {features.map((feature, index) => (
              <Card key={index} className="border-2 hover:shadow-md transition-shadow">
                <CardHeader>
                  <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-xl bg-accent">
                    <feature.icon className="h-6 w-6 text-accent-foreground" />
                  </div>
                  <CardTitle className="text-lg">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Index;
